spring:
  datasource:
    url: "jdbc:postgresql://dpg-cti392t6l47c738ejoo0-a.oregon-postgres.render.com/banking_om3j"
    username: "banking_om3j_user"
    password: "iz2Jvhr9VmwpNqnUHJTnD9TNPLMvP6J1"
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
server:
  port: 8082
