spring:
  datasource:
    url: "jdbc:postgresql://dpg-cti392t6l47c738ejoo0-a.oregon-postgres.render.com/banking_om3j"
    username: "banking_om3j_user"
    password: "iz2Jvhr9VmwpNqnUHJTnD9TNPLMvP6J1"
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
  mail:
    host: smtp.gmail.com
    port: 587
    username: duyvu2612003@gmail.com
    password: acib iqae uvdr rqmn
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 8082
