spring:
  datasource:
    url: "jdbc:postgresql://dpg-cttq751u0jms73bl7eb0-a.oregon-postgres.render.com/banking_61o6"
    username: "banking_61o6_user"
    password: "1WWldREahrLBC2Y7juvllAaVou35NTTp"
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
#    properties:
#      hibernate:
#        format_sql: true
#        show_sql: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: duyvu2612003@gmail.com
    password: acib iqae uvdr rqmn
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
#logging:
#  level:
#    org.hibernate.SQL: DEBUG  # Log câu SQL
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE  # Log giá trị thực tế của các tham số bind
server:
  port: 8082
